FSNAME=lustrarm
FSTYPE=zfs
NETTYPE=tcp
DEBUG_SIZE=1024
MOUNT=/lustre
MOUNT2=/mnt/lustre
DIR2=/mnt/lustre
DIR=/lustre
RUNAS_ID=500
RUNAS_GID=500
RUNAS='sudo -u runas'
# MDS and MDT configuration
MDSCOUNT=3

mds1_HOST="MDSMGSMACHINE1"
mds2_HOST="MDSMGSMACHINE2"
mds3_HOST="MDSMGSMACHINE3"
mgs_HOST="MDSMGSMACHINE1"
MGSNID="MDSMGSMACHINE1"
mdt_HOST="MDSMGSMACHINE1"
mdt_host="MDSMGSMACHINE1"
MDSDEV1="/dev/DEVMDSMGS"
MDSDEV2="/dev/DEVMDSMGS"
MDSDEV3="/dev/DEVMDSMGS"
MGSDEV="/dev/DEVMDSMGS"
#MGSDEV1="/dev/DEVMDSMGS"

# OSS and OST configuration
OSTCOUNT=3

ost1_HOST="OSTMACHINE1"
ost2_HOST="OSTMACHINE2"
ost3_HOST="OSTMACHINE3"
OSTDEV1="/dev/DEVOST"
OSTDEV2="/dev/DEVOST"
OSTDEV3="/dev/DEVOST"
OSTDEV="/dev/DEVOST"
OST1DEV="/dev/DEVOST"
OSSDEV="/dev/DEVOST"
OSSDEV1="/dev/DEVOST"

# Client configuration
CLIENTCOUNT=3
CLIENTS="CLIENTMACHINE1,CLIENTMACHINE2,CLIENTMACHINE3"
RCLIENTS="CLIENTMACHINE1,CLIENTMACHINE2,CLIENTMACHINE3"

PDSH="/usr/bin/pdsh -l root -S -Rssh -w"

MODOPTS_LIBCFS="libcfs_panic_on_lbug=0"
FAIL_ON_ERROR=${FAIL_ON_ERROR:-true}
PTLDEBUG=-1
SUBSYSTEM="all"
DAEMONFILE="/tmp/lustre-debug.log"
